### ISSUE TITLE
UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value

### ISSUE THREAD

**Issue by NineXYZ** [kamillobinski/chatgpt-terminal#6]
Hi, when I try to open the app it doesn't open and gives me this error.
I'm using a M1 Mac with macOS 13.4
> naishi@Arku app % python3 main.py      
Spawning browser...
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/revChatGPT/ChatGPT.py", line 431, in get_cf_cookies
    driver = uc.Chrome(
             ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 421, in __init__
    browser = subprocess.Popen(
              ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1775, in _execute_child
    and os.path.dirname(executable)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 152, in dirname
TypeError: expected str, bytes or os.PathLike object, not NoneType 
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/naishi/chatgpt-terminal/app/main.py", line 41, in <module>
    main()
  File "/Users/naishi/chatgpt-terminal/app/main.py", line 13, in main
    ai = OpenAI()
         ^^^^^^^^
  File "/Users/naishi/chatgpt-terminal/app/ai/OpenAI.py", line 9, in __init__
    self.chatbot = Chatbot({
                   ^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/revChatGPT/ChatGPT.py", line 77, in __init__
    self.get_cf_cookies()
  File "/opt/homebrew/lib/python3.11/site-packages/revChatGPT/ChatGPT.py", line 446, in get_cf_cookies
    driver.quit()
    ^^^^^^
UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value

**Comment by kamillobinski** [comment]
Thanks for submitting your pull request. I appreciate your interest in my project, but I want to let you know that this project was created solely for fun and won't be maintained or updated. Therefore, I am archiving the project.

If anyone is interested in improving, fixing, or modifying the project to suit their needs, they are more than welcome to do so on their own. However, please keep in mind that I won't be available to provide any support or assistance.
